% scrTestBeadConnectivity
close all
% define framework
 % Initialize simulator framework parameters
 obj.percentOfConnectedMonomers=[0.7];
 obj.connectedMonomers = [];
 obj.numMonomers = 50;
            obj.simulatorParams = SimulationFrameworkParams('showSimulation',true,...
                                                            'numSteps',Inf,...
                                                            'dimension',3,...
                                                            'dt',0.01,...
                                                            'diffusionConst',1,...
                                                            'objectInteraction',false);

            % create an open domain
            domainForces = ForceManagerParams('lennardJonesForce',false,...
                                             'LJPotentialWidth',0,...
                                             'LJPotentialDepth',0,...
                                             'morseForce',false,...
                                             'morsePotentialDepth',0,...
                                             'morsePotentialWidth',0,...
                                             'morseForceType','full',...
                                             'diffusionForce',false,...
                                             'diffusionConst',1,...
                                             'dt',obj.simulatorParams.simulator.dt,...
                                             'minParticleEqDistance',0);
            
            dp(1)         = DomainHandlerParams('domainShape','open',...
                                                'reflectionType','preserveEnergy',...
                                                'dimension',obj.simulatorParams.simulator.dimension,...
                                                'domainCenter',[0 0 0],...
                                                'forceParams',domainForces,...
                                                'domainWidth',4,...
                                                'dimension',obj.simulatorParams.simulator.dimension);
            obj.domainNumbers.sphere = 1; 
            % % create the polymer
            polymerForces  = ForceManagerParams('dt',obj.simulatorParams.simulator.dt,...
                                                'springForce',true,...
                                                'bendingElasticityForce',false,...
                                                'bendingConst',1,...
                                                'springConst', 1,...
                                                'bendingOpeningAngle',pi,...
                                                'minParticleEqDistance',0.5);
            if ~isempty(obj.percentOfConnectedMonomers)
            n = obj.numMonomers;
            rp = randperm(n);
            perc = floor(n*obj.percentOfConnectedMonomers);
            % make sure it is divisible by 2
            if mod(perc,2)~=0
                perc = max([perc,0]);
            end
            for pIdx = 1:(perc)/2
                obj.connectedMonomers(pIdx,:) = [rp(2*pIdx-1), rp(2*pIdx)];
            end
            
            end
            cp          = ChainParams('numBeads',obj.numMonomers,...
                                      'dimension',obj.simulatorParams.simulator.dimension,...
                                      'connectedBeads',obj.connectedMonomers,...
                                      'initializeInDomain',1,...
                                      'minBeadDistance',0,...
                                      'forceParams',polymerForces,...
                                      'b',sqrt(obj.simulatorParams.simulator.dimension));
            
     
           
            % register the object parameters in the simulator framework
            obj.simulatorParams.SetDomainParams(dp);
            obj.simulatorParams.SetChainParams(cp);
            
            
           rf= RouseSimulatorFramework(obj.simulatorParams);
           rf.Run;